version: "3"

tasks:
  debug:
    cmds:
      - go build -o $GOBIN/protoc-gen-grpc-gateway-gosdk cmd/protoc-gen-grpc-gateway-gosdk/main.go 
  install:
    deps:
      - build
    cmds:
      - cp dist/protoc-gen-grpc-gateway-gosdk_{{OS}}_{{ARCH}}/protoc-gen-grpc-gateway-gosdk $GOBIN
    silent: true
  fmt:
    cmds:
      - sh scripts/goimports.sh {{ if empty .CLI_ARGS }}all{{ else }}git{{ end }}
    silent: true
  build:
    cmds:
      - goreleaser build --snapshot --single-target --rm-dist
    silent: true
  release:
    cmds:
      - goreleaser release --rm-dist
    silent: true