name: Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/*'  
  pull_request:
    paths:
      - 'docs/*'

env:
  TZ: Asia/Shanghai

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build Vuepress
        run: |
          npm i
          npm run docs:build
          cp -r docs/.vuepress/dist .

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}